# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

before_each do |lane, options|
  gradle(task: 'clean')
end


  lane :develop do
    # gradle(task: 'clean')
    gradle(
    task: 'assemble',
    flavor: "develop",
    build_type: 'Release',
    print_command: false,
    system_properties: {
        "ENVFILE": ".env.dev.release"
      }
    # properties: {
    #   "android.injected.signing.store.file" => releaseFilePath,
    #   "android.injected.signing.store.password" => store_password,
    #   "android.injected.signing.key.alias" => "my-key-alias",
    #   "android.injected.signing.key.password" => key_password,
    # }
    )
  end
  
  desc "Create a build for staging"
  lane :staging do
    # gradle(task: 'clean')
    gradle(
      task: 'assemble',
      flavor: 'staging',
      build_type: 'Release',
      print_command: false,
      system_properties: {
        "ENVFILE": ".env.staging.release"
      }
      # properties: {
      #   "android.injected.signing.store.file" => releaseFilePath,
      #   "android.injected.signing.store.password" => store_password,
      #   "android.injected.signing.key.alias" => "my-key-alias",
      #   "android.injected.signing.key.password" => key_password,
      # }
    )  
end

desc "Create a build for QA"
lane :qa do 
# gradle(task: 'clean')
  gradle(
    task: 'assemble',
    flavor: 'qa',
    build_type: 'Release',
    print_command: false,
    system_properties: {
        "ENVFILE": ".env.qa.release"
      }
    # properties: {
    #   "android.injected.signing.store.file" => releaseFilePath,
    #   "android.injected.signing.store.password" => store_password,
    #   "android.injected.signing.key.alias" => "my-key-alias",
    #   "android.injected.signing.key.password" => key_password,
    # }
  )
  
end

# desc "Create a build for Production"
# lane :prod do 
# gradle(task: 'clean')
#   gradle(
#     task: 'assemble',
#     build_type: 'prodRelease',
#     print_command: false,
# system_properties: {
#         "ENVFILE": ".env.production.release"
#       }
#     # properties: {
#     #   "android.injected.signing.store.file" => releaseFilePath,
#     #   "android.injected.signing.store.password" => store_password,
#     #   "android.injected.signing.key.alias" => "my-key-alias",
#     #   "android.injected.signing.key.password" => key_password,
#     # }
#   )

# end


